language: node_js
node_js:
- '9.4'
install:
- yarn
- "./node_modules/gitbook-cli/bin/gitbook.js install"
- "./fetch_docs_from_catanie.sh"
script:
- "./node_modules/gitbook-cli/bin/gitbook.js build . docs"
deploy:
  provider: pages
  skip_cleanup: true
  allow_empty_commit: true
  commiter-from-gh: true
  keep_history: true
  github_token: "$GITHUB_API_TOKEN"
  local_dir: docs
  on:
    branch: master
