language: node_js
node_js:
- '12.18.312.18.312.18.312.18.312.18.312.18.312.18.312.18.312.18.312.18.3h_docs_from_catanie.sh"
script:
- "./node_modules/honkit/bin/honkit.js build . docs"
deploy:
  provider: pages
  skip_cleanup: true
  allow_empty_commit: true
  committer_from_gh: true
  keep_history: true
  github_token: "$GITHUB_TOKEN"
  local_dir: docs
  on:
    branch: master
